parse_rule: skip rule definition binder creation
boostorg/spirit pull request #646
Opened 2021-02-08 00:47 UTC by Kojoley

Not all of our parsers are constexpr constructible, and static local variable is not free for these.

Also, closes #643.

2021-02-08 09:14 UTC, cppljevans requested changes
In short, you're rm'ing the 'static auto const def' and instead inlining that def.parse.  However, not quite, AFAICT.  Shouldn't  BOOST_JOIN(rule_name, _def).rhs be the 1st arg to call_rule_definition
in order to get the RHS of the rule?

2021-02-08 16:12 UTC, cppljevans reviewed
Why not just eliminate the static and use the rule_definition:parse directly instead of inlining it?
IOW, just this one line:

  return BOOST_JOIN(rule_name, _def).parse(first, last, context, unused, attr);

2021-02-08 19:40 UTC, Kojoley commented
> Shouldn't BOOST_JOIN(rule_name, _def).rhs be the 1st arg to call_rule_definition

No

> Why not just eliminate the static and use the rule_definition:parse directly instead of inlining it?

Because a temporary is even worse than the static local.

> IOW, just this one line:
> 
> return BOOST_JOIN(rule_name, _def).parse(first, last, context, unused, attr);

This will break annotations and debug handlers.

2021-02-09 00:55 UTC, djowel commented
@Kojoley  'Some checks were not successful", can you please check? I'd like to merge this.

2021-02-09 09:23 UTC, cppljevans commented
> 
> 
> > Shouldn't BOOST_JOIN(rule_name, _def).rhs be the 1st arg to call_rule_definition
> 
> No
> 
> > Why not just eliminate the static and use the rule_definition:parse directly instead of inlining it?
> 
> Because a temporary is even worse than the static local.
> 
> > IOW, just this one line:
> > return BOOST_JOIN(rule_name, _def).parse(first, last, context, unused, attr);
> 
> This will break annotations and debug handlers.

Ah, I see my mistake.  I had assumed, based on previous views of rule_definition use, that the
BOOST_JOIN(rule_name,_def) was an instance of rule_definition.  However, now
looking at all the examples and test (in particular, the https://github.com/Kojoley/spirit/blob/parse_rule-optimization/test/x3/rule_separate_tu_grammar.cpp), that none of the _def names are rule_definitions.
Sorry for the mistake, and of course that mistake also explains why I thought BOOST_JOIN(rule_name,_def)_.parse
would be a call to rule_definition<...>::parse.  I realize now that was a rather foolish assumption :(

Sorry for noise.

2021-02-09 13:03 UTC, Kojoley commented
> @Kojoley 'Some checks were not successful", can you please check? I'd like to merge this.

Boost.Math C++11 requirement broke some of our tests, I was waiting for CI green light to push fixes to develop branch, but Travis turnaround times these days are extreme.

2021-02-09 14:22 UTC, merged